print("----------------------------------")
print("Tugas 1 SISOP Kelas B")
print("----------------------------------")
print("Nama : Dina Magdalena Manurung")
print("NPM  : 21083010117")
print("----------------------------------")
print("notes :")
print("----------------------------------")
print("Halo Dunia!")
print("Ini adalah skrip Bash pertamaku di Linux")
